apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitopsgo
spec:
  selector:
    matchLabels:
      app: gitopsgo
  template:
    metadata:
      labels:
        app: gitopsgo
    spec:
      containers:
      - name: gitopsgo
        image: gitopsgo
        ports:
        - containerPort: 8080
