apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: gitopsgo
  newName: DOCKER_USERNAME/gitopsgo
  newTag: 9862670421a6923d40db5351c5a3a52f67b1dce9
