apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: gitopsgo
  newName: gabrielhenrique18/gitopsgo
  newTag: 4ed3782e073ba5f978771f8e17c7278a502a2da8
