apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: gabrielhenrique18/gitopsgo
  newTag: newtag
- name: gostest
  newName: DOCKER_USERNAME/gitopsgo
  newTag: c72f0d7a535ace7fac2dcfef6fd90d599ae182fc
