name: GitOps
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checando o repositorio
      uses: actions/checkout@v2
    - name: Buildando a imagem
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secretes.DOCKER_PASSWORD}}
        repository: ${{ secretes.DOCKER_USERNAME}}/gitopsgo
        tags: ${{ github.sha }}, latest
         