name: GitOps
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checando o repositorio
      uses: actions/checkout@v2
    - name: Buildando a imagem
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PASSWORD}}
        repository: ${{ secrets.DOCKERHUB_USERNAME}}/gitopsgo
        tags: ${{ github.sha }}, latest

    - name: Setando o kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"
    
    - name: Atualizando os recursos do kubernetes
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
      run:  |
        cd k8s
        kustomize edit set image gostest=DOCKER_USERNAME/gitopsgo:$GITHUB_SHA

    - name: commitando
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name  "GitHub Action"
        git commit -am "Bump Docker version"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        repository: Biel-H/goWebserver
